Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from pylab import rcParams

%matplotlib inline
rcParams['figure.figsize'] = 6, 4.5

In [2]:
a = np.linspace(12, 23, 12)
a

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
b = a.reshape(2, 6)
b

array([[12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [4]:
c = a.reshape(3, 4)
c

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [5]:
d = a.reshape(4, 3)
d

array([[12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [6]:
e = a.reshape(6, 2)
e

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [7]:
f = a.reshape(12, 1)
f

array([[12.],
       [13.],
       [14.],
       [15.],
       [16.],
       [17.],
       [18.],
       [19.],
       [20.],
       [21.],
       [22.],
       [23.]])

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех 
примерах - для обозначения числа столбцов, в двух - для строк).

In [8]:
b = a.reshape(6, -1)
b

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [9]:
c =a.reshape(4, -1)
c

array([[12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [10]:
d = a.reshape(3, -1)
d

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [11]:
e = a.reshape(2, -1)
e

array([[12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [12]:
f = a.reshape(-1, 1)
f

array([[12.],
       [13.],
       [14.],
       [15.],
       [16.],
       [17.],
       [18.],
       [19.],
       [20.],
       [21.],
       [22.],
       [23.]])

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


нельзя, потому что двумерность массива подтверждается двойными скобками

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения 
со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким 
же атрибутом size, как и исходный массив.

In [13]:
t = np.random.randn(3, 4)
t

array([[-0.6025263 , -0.70045635, -2.08957576,  0.56358683],
       [ 1.8161369 , -1.24169453, -1.49715973, -0.86169316],
       [ 0.48466662, -0.44370611, -1.83423825, -2.59233374]])

In [14]:
y = t.flatten()
y

array([-0.6025263 , -0.70045635, -2.08957576,  0.56358683,  1.8161369 ,
       -1.24169453, -1.49715973, -0.86169316,  0.48466662, -0.44370611,
       -1.83423825, -2.59233374])

In [15]:
t.size == y.size

True

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [18]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с 
интервалом 2. В чем разница между массивами a и b?

In [19]:
b = a.reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [20]:
#одномерный массив а является строкой двумерного массива b

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, 
чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [25]:
a = np.zeros([2, 2])
a

array([[0., 0.],
       [0., 0.]])

In [26]:
b = np.ones([3, 2])
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
v.size

10

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, 
чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем 
транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой 
размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [29]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [32]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [33]:
B.size

16

In [34]:
np.linalg.det(B)

0.0

In [35]:
#обратную матрицу вычислить нельзя, потому что определитель матрицы В = 0

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [36]:
np.random.seed(42)

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых 
чисел от 0 до 16 невключительно.

In [38]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из 
предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [39]:
C = c.reshape(4, 4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [40]:
D = B + C
D

array([[ 11,  17,  35,  46],
       [ 24,  57,  98, 126],
       [ 29,  95, 151, 218],
       [ 42, 132, 219, 306]])

In [41]:
np.linalg.det(D)

-47196.000000000255

In [42]:
np.linalg.matrix_rank(D)

4

In [43]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.13488431,  0.07958302,  0.17988813, -0.1812018 ],
       [-0.17149758,  0.14009662,  0.147343  , -0.13687601],
       [-0.05758963,  0.01220442, -0.20404272,  0.14899568],
       [ 0.09668192, -0.08009153,  0.05778032, -0.0194508 ]])

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv 
остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и 
C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий 
элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых 
соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [44]:
D_inv = np.where(D_inv < 0, 0, 1)
D_inv

array([[1, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0]])

In [46]:
E = np.where(D_inv == 1, B, C)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [48]:
E = np.where(D_inv == 0, B, C)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [49]:
E

array([[  6,   3,  12,  32],
       [ 14,   7,  12, 122],
       [ 23,   9, 149,   6],
       [ 10, 122,   7, 302]])